---
title: "RNA_seq_DEG"
author: 'ylChen'
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
---

## 0.加载R包
```{r,eval=FALSE}
# 魔幻操作，一键清空
rm(list = ls()) 
options(stringsAsFactors = F)
# 加载airway数据集并转换为表达矩阵
library(airway,quietly = T)
library(edgeR)
```

```{r,include=FALSE}
# 加载airway数据集并转换为表达矩阵
library(airway,quietly = T)
library(edgeR)
```

## 1. 准备矩阵，分组

```{r,collapse=TRUE}
data(airway)
class(airway)

rawcount <- assay(airway)
colnames(rawcount)

# 查看表达谱
rawcount[1:3,1:3]

# 获取分组信息
group_list <- colData(airway)$dex
class(group_list)
group_list
```
## 2. 数据处理

### 2.1 过滤低表达基因

```{r,collapse=TRUE}
# 去除前的基因表达矩阵情况
dim(rawcount)

# 过滤在至少在75%的样本中都有表达的基因
keep <- rowSums(rawcount>0) >= floor(0.75*ncol(rawcount))
table(keep)

filter_count <- rawcount[keep,]
filter_count[1:3,1:3]
dim(filter_count)
```
### 2.2 cpm标准化（针对counts）

```{r,collapse=TRUE}
# 加载edgeR包计算counts per millio(cpm) 表达矩阵,并对结果取log2值
express_cpm <- log2(cpm(filter_count)+1)
express_cpm[1:3,1:3]

# 保存表达矩阵和分组结果
save(filter_count,express_cpm,group_list,file = "../data/input_DEG.rdata")
```



