---
title: "step03-DESeq2_DEG"
author: 'ylChen'
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
---

## 0. 加载

```{r,collapse=TRUE}
rm(list = ls())
options(stringsAsFactors = F)

# 读取基因表达矩阵信息
lname <- load(file = "../data/input_DEG.rdata")
lname 

# 查看分组信息和表达矩阵数据
# 此为原始counts，不是cpm
exprSet <- filter_count
dim(exprSet)
exprSet[1:3,1:3]
table(group_list)
```

```{r,include=FALSE}
library(DESeq2)
```


## 1. 差异分析

```{r,collapse=TRUE}

DESeq2_DEG <- function(exprSet,group_list){
# 加载包
#library(DESeq2)

# 第一步，构建DESeq2的DESeq对象
colData <- data.frame(row.names=colnames(exprSet),group_list=group_list)
dds <- DESeqDataSetFromMatrix(countData = exprSet,colData = colData,design = ~ group_list)

# 第二步，进行差异表达分析
dds2 <- DESeq(dds)

# 提取差异分析结果，trt组对untrt组的差异分析结果
tmp <- results(dds2,contrast=c("group_list","trt","untrt"))
DEG_DESeq2 <- as.data.frame(tmp[order(tmp$padj),])
#head(DEG_DESeq2)

# 去除差异分析结果中包含NA值的行
DEG_DESeq2 = na.omit(DEG_DESeq2) }

# 运行
DEG_DESeq2 <- DESeq2_DEG(exprSet = exprSet,group_list = group_list)

head(DEG_DESeq2)
save(DEG_DESeq2,file = '../data/DEG_DESeq2.rdata')

```



