---
title: "step3-limma_DEG"
author: 'ylChen'
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
---

## 0. 加载

```{r,collapse=TRUE}
rm(list = ls())
options(stringsAsFactors = F)

# 读取基因表达矩阵信息
lname <- load(file = "../data/input_DEG.rdata")
lname 

# 查看分组信息和表达矩阵数据
# 此为原始counts，不是cpm
exprSet <- filter_count
dim(exprSet)
exprSet[1:3,1:3]
table(group_list)
```

```{r,include=FALSE}
library(limma)
library(edgeR)
```

## 1. 差异分析

```{r,collapse=TRUE}
limma_DEG <- function(exprSet,group_list){
  ## 第一步，创建设计矩阵和对比：假设数据符合正态分布，构建线性模型
# 0代表x线性模型的截距为0
design <- model.matrix(~0+factor(group_list))
colnames(design) <- levels(factor(group_list))
rownames(design) <- colnames(exprSet)
#design

# 设置需要进行对比的分组，需要修改
comp <- 'trt-untrt'
cont.matrix <- makeContrasts(contrasts=c(comp),levels = design)

## 第二步，进行差异表达分析
# 将表达矩阵转换为edgeR的DGEList对象
dge <- DGEList(counts=exprSet)

# 进行标准化
dge <- calcNormFactors(dge)   

#Use voom() [15] to convert the read counts to log2-cpm, with associated weights, ready for linear modelling:
v <- voom(dge,design,plot=TRUE, normalize="quantile") 
fit <- lmFit(v, design)
fit2 <- contrasts.fit(fit,cont.matrix)
fit2 <- eBayes(fit2)

## 第三步，提取过滤差异分析结果
tmp <- topTable(fit2, coef=comp, n=Inf,adjust.method="BH")
DEG_limma_voom <- na.omit(tmp)
DEG_limma_voom
}

DEG_limma_voom <- limma_DEG(exprSet = exprSet,group_list = group_list)
head(DEG_limma_voom)
```

