---
title: "step3-edgeR_DEG"
author: 'ylChen'
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
---


## 0. 加载

```{r,collapse=TRUE}
rm(list = ls())
options(stringsAsFactors = F)

# 读取基因表达矩阵信息
lname <- load(file = "../data/input_DEG.rdata")
lname 

# 查看分组信息和表达矩阵数据
# 此为原始counts，不是cpm
exprSet <- filter_count
dim(exprSet)
exprSet[1:3,1:3]
table(group_list)
```

```{r,include=FALSE}
library(edgeR)
```

## 1. 差异分析

```{r,collapse=TRUE}
edgeR_DEG <- function(exprSet,group_list){
  # 假设数据符合正态分布，构建线性模型。0代表x线性模型的截距为0
design <- model.matrix(~0+factor(group_list))
rownames(design) <- colnames(exprSet)
colnames(design) <- levels(factor(group_list))
#design

# 构建edgeR的DGEList对象
DEG <- DGEList(counts=exprSet,group=factor(group_list))

# 增加一列$norm.factors
DEG$samples$lib.size <- colSums(DEG$counts)
DEG$samples

# 归一化基因表达分布
DEG <- calcNormFactors(DEG)

# 计算线性模型的参数
DEG <- estimateGLMCommonDisp(DEG,design)
DEG <- estimateGLMTrendedDisp(DEG, design)
DEG <- estimateGLMTagwiseDisp(DEG, design)

# 拟合线性模型
fit <- glmFit(DEG, design)

# 进行差异分析，1,-1意味着前比后
lrt <- glmLRT(fit, contrast=c(1,-1)) 

# 提取过滤差异分析结果
DEG_edgeR <- as.data.frame(topTags(lrt, n=nrow(DEG)))
DEG_edgeR
}

DEG_edgeR <- edgeR_DEG(exprSet = exprSet,group_list = group_list)

head(DEG_edgeR)
```



